### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by dustinlacewell** [Schniz/cmd-ts#113]
I am looking for the right TS command framework for me and am curious about the future of this project.

**Comment by Schniz** [comment]
Hi! Appreciate your interest. This is my go-to command line argument parser as of today. Haven't found anything nicer than this so far. Some internal projects at work use this as well with great results.

**Comment by dustinlacewell** [comment]
I have found it useful as well, thanks for the work. I have just run into a few issues and was curious about the velocity of the project. Thanks for your reply.
