### ISSUE TITLE
v0.9.0 is published but not in version control

### ISSUE THREAD

**Issue by haltcase** [Schniz/cmd-ts#135]
v0.9.0 is published to npm:

![image](https://user-images.githubusercontent.com/16605186/147801039-4dfd780f-9038-4c98-8b9b-17ab6ed14698.png)

The repo here doesn't seem to reflect all those changes, and there's no tag for that version or any release notes.

https://github.com/Schniz/cmd-ts/blob/e1b65d26be16db3db1630b229ba9a155fd6bc1ab/package.json#L3

**Comment by Schniz** [comment]
Oops. That’s right. Unfortunately I returned the computer which I published it from. I will publish 0.9.1 soon just so it will be easy to know what’s in the release (current main branch). 

I must set up a GH action that publishes instead

**Comment by Schniz** [comment]
Done
