### ISSUE TITLE
add ability to use `-h` argument as custom arg

### ISSUE THREAD

**Issue by DanielKag** [Schniz/cmd-ts#136]
for example, I need to pass to my CLI `-h` for `headless` mode.
I can't do that right now because it will show me the help menu instead.

**Comment by DanielKag** [comment]
I create a small PR that adds the ability to change the short identifier of the help to something else from the config.
Unfortunately I don't have permission to push a PR.

**Comment by Schniz** [comment]
What do you mean? Probably need to fork it first?

**Comment by DanielKag** [comment]
You were right.
Here is my pr, I haven't run it though...
https://github.com/Schniz/cmd-ts/pull/137

**Comment by DanielKag** [comment]
This is my workaround for now...

```
const newArgs = []
for (const arg of process.argv) {
  if (arg === '-h') {
	  newArgs.push('--headless')
  } else if (arg.startsWith('-') && !arg.startsWith('--') && arg.includes('h')) {
	  newArgs.push('--headless')
	  newArgs.push(arg.replace('h', ''))
  } else {
	  newArgs.push(arg)
  }
}

run(binary(cmd), newArgs).catch((err) => {
process.exitCode = process.exitCode || 1
console.error('An error occured', err)

```

**Comment by Schniz** [comment]
I personally believe that you should not use `-h` and use `-H` instead, as `-h` is sort of a standard in CLIs for showing help (node, python, vim, all use `-h` for it)

**Comment by DanielKag** [comment]
I agree, we have an inside tool that uses this convention for `--headless` mode and devs are already got used to using it.
I can keep the work around as it works well.

**Comment by Schniz** [comment]
thanks! closing. maybe in the future we will be able to support it, but we need to rethink the parser for it for this feature to really work well
