### ISSUE TITLE
Support for required arguments

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Schniz/cmd-ts#209]
There doesn't seem to be any support for requiring that arguments are present? I skimmed the implementation briefly, but I'm not seeing anything about requiring positionals.

This is also a bigger issue since the implementation uses a `handler` instead of returning optional values; since the `handler` will never get called, I have to do my own validation _outside_ of `cmd-ts`, which … largely defeats the purpose of it. :P

**Comment by Schniz** [comment]
All arguments are required unless wrapped in `optional`!
