### ISSUE TITLE
oneOf combined with optional doesn't seem to make the union of literals optional

### ISSUE THREAD

**Issue by drwlrsn** [Schniz/cmd-ts#59]
I am probably not doing something correctly, but combining say, `optional(oneOf(['on', 'off']))` doesn't result in the type `'on' | 'off' | undefined`.

<img width="699" alt="Screen Shot 2021-01-19 at 8 28 21 AM" src="https://user-images.githubusercontent.com/981387/105048252-f75e1400-5a30-11eb-88b1-eeeda3b74c44.png">

**Comment by Schniz** [comment]
Hi!
Do you have `tsconfig.json` with strict mode on?

**Comment by drwlrsn** [comment]
Ah! That's what it is... in this project strict mode is off. Dang

**Comment by Schniz** [comment]
All good. The first time I gave my [Typing The Technical Interview](https://gal.hagever.com/posts/typing-the-technical-interview-in-typescript/) talk I forgot to set up a `tsconfig.json` and the default is not strict. It was very awkward. 😃 

Happy that it got solved. 😃
