### ISSUE TITLE
How to deal with floats

### ISSUE THREAD

**Issue by elderapo** [Schniz/cmd-ts#76]
I've only found this in docs:
```
- Some arguments may be an integer; so providing a float should result in an error
```
however when I pass a float ex. `0.22` it parses to `0`.

**Comment by Schniz** [comment]
Ah damn. Looks like I used `parseInt` instead of `parseFloat`. Do you want to open a PR? 

https://github.com/Schniz/cmd-ts/blob/434fe9b89857bab41d61c69b512b9972bf531a8f/src/types.ts#L10

**Comment by elderapo** [comment]
@Schniz Here you go #77. Didn't fully understand the tests but tried to write some. Let me know if it's enough.

Btw. congratz on a very nice library :)
