### ISSUE TITLE
Add `aliases` to `subcommands`

### ISSUE THREAD

**Issue by chuckwondo** [Schniz/cmd-ts#79]
Unless I'm missing something or using things incorrectly, it is not possible to specify aliases for "parent" commands that use `subcommands`.  Only "leaf" commands can be aliased.  It would be nice to be able to alias "parent" commands.

**Comment by Schniz** [comment]
Maybe we don’t fully understand the issue? What does it mean parent command?

**Comment by chuckwondo** [comment]
Sorry, I must have missed `aliases` as part of a regular command (top level, not subcommand), but I see it now, given the link to the code. Not sure how I missed it.
