### ISSUE TITLE
Negative Numbers and Strings starting with "-" are not parsed

### ISSUE THREAD

**Issue by kastenbutt** [Schniz/cmd-ts#81]
Hello everyone, thanks to @Schniz for this neat library!

I've run into a problem with negative numbers and strings starting with "-".  Given this configuration:

```typescript
command({
    name: 'show-my-number',
    args: {
        myNumber: positional({
            type: number,
            displayName: 'my-number',
        }),
    },
    handler: (args) => {
        console.log(`This is my number: ${args.myNumber}`)
    }
})
```

When I run `show-my-number -10`, I get:
> error: found 2 errors
>
>   -10
>    ^ Unknown arguments
>
> Along the following error:
>   2. No value provided for my-number

This also occurs when setting the type of `myNumber` to `string`, as well as when using `optional` instead of `positional`.

**Comment by Schniz** [comment]
Hi! That's an interesting use case. Are we sure that `option` does not work? As far as parsing goes, `bin/app -10` will be parsed as `{positional bin/app} {flag 10}`

Can you try forcing positional arguments? `bin/app -- -10`

P.S. I'm afk for the following week. Sorry for the delay I will probably have in the discussion

**Comment by kastenbutt** [comment]
Yes, I'm sure `option` does not work. I checked again and get the same error. I tried forcing positional arguments as you suggested but it didn't help either.

**Comment by Schniz** [comment]
Very interesting! I'll take a look. Sorry for the delay.

**Comment by kastenbutt** [comment]
Thanks for your work and the promt resolution! 🎉
